- hosts: localhost
  connection: local

  tasks:
    - name: Delete Kubernetes namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ namespace }}"
        state: absent
