- name: Listen for newly added resources
  hosts: all
  sources:
    - ansible.eda.webhook:
        hosts: 0.0.0.0
        port: 5000
  rules:
    - name: Notify to Slack when a namespace has been created
      condition: event.payload.eventmeta.kind == 'Namespace' and event.payload.eventmeta.reason == 'Created'
      action:
        run_playbook: 
          name: notify-namespace-created.yml
          extra_vars:
            token: "{{ slack_token }}"
            msg: "{{ event.payload.text }}"
